### ISSUE TITLE
Upcoming minor release items

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#685]
### Mandatory

__ADDITIONAL (GENERAL):__
- [x] _~~Workaround solutions for iOS/macOS data loss risk issues:~~ **DONE**_
  - [x] _~~compile with `SQLITE_THREADSAFE=2` again ref: #703~~ **DONE**_
  - [x] _~~workaround solution for iOS threading issue reported in #716~~ **DONE**_
- [ ] _Deal with Windows app store issue discussed in #563 in documentation and maybe build._
- [x] _~~Add `/SAFESH` as described in:~~ **DONE**_
  - _~~https://github.com/litehelpers/Cordova-sqlite-storage/issues/563#issuecomment-287648222~~_
  - _~~https://msdn.microsoft.com/en-us/library/9a89h429.aspx~~_

#### Documentation

- [ ] Pitfalls of using WAL ref: litehelpers/Cordova-sqlite-help#10
- [ ] Use with https://github.com/dpa99c/cordova-sqlite-porter ref: litehelpers/Cordova-sqlite-help#26
- [ ] Other prepopulated database documentation items ref: litehelpers/Cordova-sqlite-help#26

_ADDITIONAL:_
- [x] _~~Note that standard transaction mechanism is no longer recommended and to be deprecated ref: #690~~ **DONE**_
- [x] _~~Document "multiple sqlite problem risk" ref: #626~~ **DONE**_
- [ ] _TBD Document safest settings to use for database on Android ref: #671_

#### Feature(s)

_UPDATE: Moved to major release ref: #687 due to time/schedule constraint:_
- [ ] ~~Function to get database directory path ref: litehelpers/Cordova-sqlite-storage#680 (may be affected by litehelpers/Cordova-sqlite-storage#681: Database storage in arbitrary path Android/iOS/macOS/Windows)~~

#### Documentation

- [ ] Document why Windows AnyCPU target is not possible ref: litehelpers/Cordova-sqlite-help#19
- [ ] Documentation of single-statement API ref: litehelpers/Cordova-sqlite-help#17
- [ ] Statement of compliance to Web SQL Database DRAFT API ref: litehelpers/Cordova-sqlite-storage#553

#### Testing

- [ ] Extremely large/small values ref: litehelpers/Cordova-sqlite-storage#627

_ADDITIONAL:_
- [ ] _Test with advanced features such as JOIN & VIEW ref: litehelpers/Cordova-sqlite-storage#658_

#### Fixes & features

_UPDATE: these updates are expected to come in the major release ref: #687_
- CREATE database if it does not exist should be optional ref: litehelpers/Cordova-sqlite-storage#212
- Database storage in arbitrary path (Android/iOS/macOS/Windows) ref: litehelpers/Cordova-sqlite-storage#681
- Deprecate other iOS database locations ref: litehelpers/Cordova-sqlite-storage#682

_ADDITIONAL, **HIGHLY DESIRED before major release** ~~now expected to come in the major release ref: #687~~_
-  [ ] _Use UTF-8 encoding for Windows ref: litehelpers/Cordova-sqlite-storage#652_
- [ ] _~~TBD **better** cleanup of "new transaction is waiting for open operation" log messages ref: litehelpers/Cordova-sqlite-storage#679~~_
- [ ] _SQLite3 compile options such as HAVE_USLEEP & NDEBUG for closer match to sqlcipher version_
- [ ] _Integrate fix contributed in litehelpers/Cordova-sqlite-storage#709 to handle NULL ( `u0000`) characters on Windows platform_
- [ ] _Should refuse to open new database files after `onDestroy` on Android has been called, equivalent on iOS ref: PR #697_
- [ ] _Update needed to work with cordova-android@7 ref: #729_
- [x] _~~builtin android.database end transaction if active before closing (8192bc841487252762cbeaf50587c1de30767186) ref:#730~~ DONE_
- [ ] _Bind all numbers as REAL numbers ref: litehelpers/Cordova-sqlite-storage#684 possibly before major release_
- [ ] _TBD (possibly related to litehelpers/Cordova-sqlite-storage#684): builtin android.database implementation seems to treat numeric parameter argument values as string values, needs investigation ref: <https://github.com/litehelpers/Cordova-sqlite-storage/pull/730#issuecomment-350918898>_
- [ ] _~~TBD for investigation: PRAGMA journal_mode should be same value on builtin android.database implementation, default Android-sqlite-connector implementation, and other platforms ref: <https://github.com/litehelpers/Cordova-sqlite-storage/pull/730#issuecomment-350919989>~~ WILL NOT BE CHANGED: PRAGMA journal_mode reports `delete` in case of default android.database implementation (same as other platform implementations) on Android 8.1_
- [ ] _Fix broken Circle/Travis CI or remove_
- [ ] _JavaScript remove qid no longer needed & other cleanup_
- [ ] _Fix for builtin android.database implementation on Turkish and other foreign locales in PR #713_
- [x] _PR #657: Add plugin typings from DefinitelyTyped_
- [ ] _address iOS/macOS resource leak when deleting database without closing first_

- _Use extra durable build option as described in <https://github.com/litehelpers/Cordova-sqlite-storage/issues/736#issuecomment-357123554>_
- _review any other possible causes of database corruption ~~ref: #736~~ TBD_
- _iOS/macOS platform version openDatabase checks from <https://github.com/brodybits/cordova-sqlite-evmax-legacy-exp-free>_
- _Resolve issue with PSPDFKit ref: <https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/59>_
- _Windows implementation should include an error object when signaling a close error_
- _Resolve INCORRECT error code / INCONSISTENT error messages on Windows_
- _TBD include actual error code, perhaps in error message (already done on builtin android.database implementation in case of androidDatabaseImplementation: 2 on Android)_
- _Include info about prepare statement error vs execute statement error, as done on Windows_
- _testing with PRAGMA foreign_keys ref: <https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free/issues/23>_
- _test/document issue with Unicode column name ref: #641._
- _improve testing & documentation related to Unicode characters on Android ref: #739_
- _document existence of spatialite fork_
- _pointer to <https://github.com/Crypho/cordova-plugin-secure-storage>_

_ADDITIONAL DOCUMENTATION:_

- _<https://devdactic.com/ionic-sqlite-queries-database/> - using cordova-sqlite-storage with sqlite-porter_
- _<https://www.thepolyglotdeveloper.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/>_
- _<https://www.thepolyglotdeveloper.com/2015/01/deploy-ionic-framework-app-pre-filled-sqlite-db/> - using [an-rahulpandey / cordova-plugin-dbcopy](https://github.com/an-rahulpandey/cordova-plugin-dbcopy) with cordova-sqlite-storage_
- _<https://github.com/nolanlawson/cordova-prepopulated-database-demo> (pre-populated demo with sqlite plugin 2)_
- _<https://codesundar.com/lesson/cordova-sqlite-storage/>_
- _<http://blog.bradleygore.com/2015/09/25/cordova-sqlite-migrations/>_
- _<http://blog.bradleygore.com/2015/08/24/getting-started-with-cordova-sqlite/>_
- _Additional items from prepopulated database documentation updates in <https://github.com/litehelpers/Cordova-sqlite-help/issues/26>_
- _<https://www.thepolyglotdeveloper.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/>_
- _<https://devdactic.com/ionic-sqlite-queries-database/> - using cordova-sqlite-storage with sqlite-porter_
- _possible Android content provider solution ref: <https://github.com/litehelpers/Cordova-sqlite-help/issues/9>_

_MAJOR DOCUMENTATION CLEANUP NEEDED here or in NEXT MAJOR RELEASE (#687) ref: <https://github.com/litehelpers/Cordova-sqlite-help/issues/33> & <https://github.com/litehelpers/Cordova-sqlite-storage/issues/596#issuecomment-351980903>_

### Timeline

~~4-6 weeks due to existing backlog~~

**Comment by jabawack81** [comment]
@brodybits there is any update on the timeline for this release? I'm interested particularly in the fix for the issue #563 

Thanks

**Comment by brody2consult** [comment]
My apologies for the delay that was due to workload. I will probably need another 1-2 months and *may* combine with major release in #687.

@jabawack81 workaround for #563 is to fix it yourself in a fork or with help from [npmjs.com / patch-package](https://npmjs.com/patch-package).

**Comment by jabawack81** [comment]
@brodybits I would love to if I knew what to fix.

**Comment by brody2consult** [comment]
@jabawack81 the /SAFESEH build flag for Win32 is now integrated with this plugin version as well as cordova-sqlite-ext. Please report if it helps or not.

**Comment by brody2consult** [comment]
cordova-sqlite-storage 2.1.0 & 2.1.1 released with some changes discussed here:
- Workaround solutions for iOS/macOS data loss risk issues:
  - compile with `SQLITE_THREADSAFE=2` again ref: #703
  - workaround solution for iOS threading issue reported in #716
- Add `/SAFESH` as described in:
  - https://github.com/litehelpers/Cordova-sqlite-storage/issues/563#issuecomment-287648222
  - https://msdn.microsoft.com/en-us/library/9a89h429.aspx
- Document "multiple sqlite problem risk" ref: #626 
- _Possible extra cleanup of "new transaction is waiting for open operation" log messages_

along with a couple additional changes from pull requests:
- Suppress warnings for sqlite3.c & PSPDFThreadSafeMutableDictionary.m on iOS/macOS ref: litehelpers/Cordova-sqlite-storage#569
- style(package): add macOS Platform to package.json litehelpers/Cordova-sqlite-storage#695

**Comment by jabawack81** [comment]
I Brody I got the same error.

My test procedure:

- I've deleted the plugin, platform and node_modules folder from my cordova project 
- updated cordova-sqlite-storage to 2.1.2
- run cordova prepare from the powershell
- from visualstudio 2017 project->store->create app packages...

and got this error:


    ------ Building platform: windows
    ------ Build configuration options:  --release -- --win --archs "x86 arm"
    No scripts found for hook "before_compile".
    PlatformApi successfully found for platform windows
    Reading build config file: C:[PROJECTFOLDER]\build.json
    Running command: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" -version -nologo
    Command finished with error code 0: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe -version,-nologo
    Using MSBuild v15.1 from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
    Building project: C:[PROJECTFOLDER]\platforms\windows\CordovaApp.Windows10.jsproj
      Configuration : release
      Platform      : x86
    Running command: C:\WINDOWS\system32\reg.exe query "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows" /s /v InstallationFolder /reg:32
    Command finished with error code 0: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows,/s,/v,InstallationFolder,/reg:32
    Running command: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" C:[PROJECTFOLDER]\platforms\windows\CordovaApp.Windows10.jsproj /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=release /p:Platform=x86 /p:AppxBundle=Never /p:UapAppxPackageBuildMode=StoreUpload
      Patching 10 in prebuild event...
      Injected base.js reference to the /www/index.html
      Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
      Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): error MSB3030: Could not copy the file "C:[PROJECTFOLDER]\plugins\cordova-sqlite-storage\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\Debug\SQLite3.UWP\SQLite3.winmd" because it was not found. [C:[PROJECTFOLDER]\platforms\windows\CordovaApp.Windows10.jsproj]
    Command finished with error code 1: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe C:[PROJECTFOLDER]\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=release,/p:Platform=x86,/p:AppxBundle=Never,/p:UapAppxPackageBuildMode=StoreUpload
    1>MSBUILD : cordova-build error : Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe: Command failed with exit code 1
    1>Done building project "project.jsproj" -- FAILED.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
    ========== Package: 0 succeeded, 2 failed ===========

**Comment by brody2consult** [comment]
@jabawack81 I just updated <https://github.com/brodybits/cordova-sqlite-storage-starter-app> and was able to create a Windows app package from project -> store -> create app packages (with a test certificate, I did not create the app package for the app store but this part should not matter). In general `cordova prepare` is not necessary if you do `cordova platform add windows` with the plugins already configured in `config.xml`. In case of any further issues:
- First give it a try with <https://github.com/brodybits/cordova-sqlite-storage-starter-app> or <https://github.com/brodybits/cordova-sqlite-test-app> (you have to explicitly add the desired sqlite plugin version in case of cordova-sqlite-test-app). In case this does not work please raise a new issue with as much detail as possible.
- Assuming this works for you in <https://github.com/brodybits/cordova-sqlite-storage-starter-app> then I would suggest you try one thing at a time until you find out what does and does not work for you. In case you find anything else please raise a new issue with a minimal, self-contained reproduction project.

**Comment by sergii-trotsiuk** [comment]
Hi guys, any news about next release? I get bug on Windows 10 https://github.com/litehelpers/Cordova-sqlite-storage/pull/709
How can I help with next release that will include this fix?

**Comment by bojanbizjak** [comment]
Is there any plan or possibility that spatialite will be integrated or can be used with any of supported plugin versions?

**Comment by brody2consult** [comment]
Spatialite is already discussed in <https://github.com/xpbrew/cordova-sqlite-storage-help/issues/32>.

**Comment by brody2consult** [comment]
At this point I am giving top priority to a newly redesigned plugin version which is in progress at this time, discussed in <https://github.com/brodybits/ask-me-anything/issues/3>.

Priority for other items is given to paid customers. Please feel free to reach out to [chris.brody+brodybits@gmail.com](mailto:chris.brody+brodybits@gmail.com) or [sales@xpbrew.com](mailto:sales@xpbrew.com) in case of interest.
